# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev , main ]
  pull_request:
    branches: [ dev , main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name : Extract version
      id: vars
      run: echo ::set-output name=version::(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Swaggerresponse
      run: echo ${{ steps.vars.outputs.version }} 
    - name : Publish version
      uses: fjogeleit/http-request-action@v1
      id: swaggereq
      with:
        url: 'https://api.swaggerhub.com/apis/POC-MG_1/${{ github.event.repository.name }}/${{ steps.vars.outputs.version }}/settings/lifecycle?force=true'
        method: 'PUT'
        bearerToken: '5ce4a89d-4d60-4248-ba8f-457f18cc2156'
      if: github.ref == 'refs/heads/main'
    - name: Swaggerresponse
      run: echo ${{ steps.swaggereq.outputs.response }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dswagger.org=POC-MG_1 -Dswagger.token=5ce4a89d-4d60-4248-ba8f-457f18cc2156
      
